name: Salesforce CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate with Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo $SFDX_AUTH_URL > ./sfdx_auth.txt
          sfdx auth:sfdxurl:store -f ./sfdx_auth.txt -a DevOrg

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -u DevOrg -p force-app
