name: Deploy to Salesforce

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with Salesforce using JWT
        run: |
          sf auth:jwt:grant --client-id <ConsumerKey> \
                            --jwt-key-file <(echo "$JWT_PRIVATE_KEY") \
                            --username <SalesforceUsername> \
                            --instance-url https://test.salesforce.com
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}

      - name: Deploy metadata
        run: sf project deploy start --target-org <SalesforceUsername>
