name: Deploy to Salesforce

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          curl -sL https://developer.salesforce.com/media/salesforce-cli/sf/install | bash
          sf version

      - name: Authenticate with Salesforce
        run: sf org login sfdx-url --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
        env: 
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          
      - name: Deploy metadata
        run: sf project deploy start --target-org DevOrg
