name: Deploy to Salesforce

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Verify Salesforce CLI installation
        run: sf version

      - name: Authenticate with Salesforce
        run: sf org login sfdx-url --sfdx-url-file <(echo "$SFDX_AUTH_URL")
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}

      - name: Deploy metadata
        run: sf project deploy start --target-org DevOrg
